#!/usr/bin/env python3
"""Emit docs/PARTY_COUNT_WRITERS.md from the acquisition inventory.

The table is GENERATED from check_acquisition_paths.py's INVENTORY so the two
cannot drift. If a row here disagrees with the checker, this file is the thing
that is wrong -- regenerate it.

Run:  python3 tools/character_mode/emit_party_writer_doc.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "tests"))

import check_acquisition_paths as chk          # noqa: E402

ORDER = {"UNGATED": 0, "UNVERIFIED": 1, "GATED": 2, "NOT-A-WRITER": 3,
         "EXEMPT": 4}

PREAMBLE = """# Party-count writers -- what each one actually is

**GENERATED by `tools/character_mode/emit_party_writer_doc.py` from
`tools/tests/check_acquisition_paths.py`. Do not hand-edit the table.**

`check_acquisition_paths.py` enumerates every instruction in this ROM that
stores through a pointer to `gPlayerPartyCount`, on the reasoning that anything
handing the player a Pokemon must eventually touch that byte. It proves the SET
of writers has not changed; it does **not** prove each one is gated. This file
records what reverse engineering found each one to be.

Verdicts: **UNGATED** -- measured, reachable, and covered by NO gate: a known
hole. **GATED** -- the project's enforcement covers it. **EXEMPT** --
deliberately not gated, with the reason. **NOT-A-WRITER** -- the scan reports
it, RE showed it is a read (see the detector note). **UNVERIFIED** -- a real
"go look", not a clean bill of health.

An UNGATED row is pinned by `EXPECT_UNGATED` in the checker rather than failing
the suite, so a SECOND hole fails loudly while a recorded, understood one waits
on a design decision. A checker that is permanently red is a checker nobody
runs -- this workspace has had exactly that happen once already.

## Two things that generalise, and both bite

### The LAUNDERING hole in this primitive

A recount (`gPlayerPartyCount = 0; ++ per non-empty slot`) is the commonest
shape in every one of these ROMs, and it is EXEMPT because it introduces
nothing. But it is also what makes a *direct* write into `gPlayerParty`
legitimate afterwards. So the party-count byte is an excellent primitive for
catching a routine that *adds* a mon and a poor one for catching a routine that
*writes the array and lets someone else recount*. That is the Platinum lesson --
*an inventory is only as good as its choice of PRIMITIVE* -- recurring one level
up rather than one idiom over. **A future pass should inventory writers of
`gPlayerParty` itself and reconcile the two sets.**

### The DETECTOR DEFECT that produces NOT-A-WRITER rows

The scan finds `ldr rX,[pc,#imm]` loading the count's address, then looks ahead
up to 60 instructions for a store through `rX`. It breaks on a re-`ldr` of
`rX`, on `bx`, and on `pop {..,pc}` -- but **not** when `rX` is clobbered by an
ordinary instruction (`ldrb rX,[rX]`, `movs rX,rY`), and **not** at an
unconditional branch, so the window can walk into a literal pool and decode a
data word as a store.

Both failure modes were confirmed here. They are safe -- the detector
over-reports, it does not miss -- so the sites stay inventoried rather than
being filtered out: dropping them would make the "nothing inventoried vanished"
check fail. Tightening the detector is a deliberate future change that must
re-baseline the inventory in the same commit.

"""

FOOTER = """
## Method, so it can be repeated

1. `arm-none-eabi-objdump -b binary -m armv4t -M force-thumb -D
   --adjust-vma=0x08000000 --start-address=... --stop-address=...`
2. Resolve the pc-relative pool by hand: `((pc + 4) & ~3) + imm * 4`.
3. Find the containing function by the nearest preceding `push {..,lr}` --
   then **verify it** by finding BL callers or pointer references to that
   entry. Where a candidate entry has neither, it is a mid-function push and
   the real entry is earlier; that happened twice here and both times the
   naive answer would have been wrong.
4. For a site claimed dead, scan the whole ROM for BL, `b`, `b<cond>` and u32
   pointers landing inside the orphaned range -- and read what any hits
   actually are. Coincidental matches inside sample data look exactly like
   pointer-table entries until you print their neighbours.
"""


SECOND = """
---

# The other half: mon-sized copies INTO gPlayerParty

`tools/tests/check_party_writes.py` is the second inventory, and it exists
because of the LAUNDERING HOLE above: a recount is EXEMPT precisely because it
introduces nothing, and that is exactly what makes a direct write into
gPlayerParty legitimate afterwards. It pins every call whose destination is a
gPlayerParty slot and whose size argument is the mon size -- a species can only
enter a slot as a whole-mon copy, and the size argument is what separates the
copies from the reads.

⚠️ **Choosing that primitive took three tries, and the failures are the useful
part.** "Every store through a party-derived pointer" gave 261 candidates.
"Every function called with a party pointer in r0" gave ~171 callees, because
`GetMonData(&gPlayerParty[i], ...)` passes the mon in r0 too -- at that
resolution a read is indistinguishable from a write. Only the size argument
cuts it to a set a person can actually read.

⚠️ **And the first working version had a blind spot that hid the enforcement
copy itself.** It treated a pc-relative reload of ANY tracked register as the
end of the window; CFRU's `GiveMonToPlayer` reloads the register that held
gPlayerParty long after the slot pointer has been computed into r0, so its own
copy went unseen -- and the "at least one GATED copy is present" check failed,
which is how it was noticed. It now drops just that register and keeps going.
**A checker whose anchor assertion fails is telling you about the checker.**
"""


def main():
    rows = sorted(chk.INVENTORY.items(),
                  key=lambda kv: (ORDER.get(kv[1][0], 9), kv[0]))
    out = [PREAMBLE, "## %s -- %d inventoried writer site(s)\n"
           % (chk.GAME, len(chk.INVENTORY))]
    for off, (verdict, why) in rows:
        out.append("### `%#010x` (file `%#010x`) -- **%s**\n"
                   % (0x08000000 + off, off, verdict))
        out.append(why + "\n")
    try:
        import check_party_writes as pw
    except Exception:
        pw = None
    if pw is not None:
        out.append(SECOND)
        out.append("## %d inventoried copy site(s)\n" % len(pw.INVENTORY))
        for off, (verdict, why) in sorted(
                pw.INVENTORY.items(),
                key=lambda kv: (ORDER.get(kv[1][0], 9), kv[0])):
            out.append("### `%#010x` (file `%#010x`) -- **%s**\n"
                       % (0x08000000 + off, off, verdict))
            out.append(why + "\n")
    out.append(FOOTER)
    path = os.path.join(ROOT, "docs", "PARTY_COUNT_WRITERS.md")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote %s -- %d sites" % (os.path.relpath(path, ROOT),
                                    len(chk.INVENTORY)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
