#!/usr/bin/env python3
"""Emit docs/PARTY_COUNT_WRITERS.md from the acquisition inventory.

The table is GENERATED from check_acquisition_paths.py's INVENTORY so the two
cannot drift. If a row here disagrees with the checker, this file is the thing
that is wrong -- regenerate it.

Run:  python3 tools/character_mode/emit_party_writer_doc.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "tests"))

import check_acquisition_paths as chk          # noqa: E402

ORDER = {"UNVERIFIED": 0, "GATED": 1, "NOT-A-WRITER": 2, "EXEMPT": 3}

PREAMBLE = """# Party-count writers -- what each one actually is

**GENERATED by `tools/character_mode/emit_party_writer_doc.py` from
`tools/tests/check_acquisition_paths.py`. Do not hand-edit the table.**

`check_acquisition_paths.py` enumerates every instruction in this ROM that
stores through a pointer to `gPlayerPartyCount`, on the reasoning that anything
handing the player a Pokemon must eventually touch that byte. It proves the SET
of writers has not changed; it does **not** prove each one is gated. This file
records what reverse engineering found each one to be.

Verdicts: **GATED** -- the project's enforcement covers it. **EXEMPT** --
deliberately not gated, with the reason. **NOT-A-WRITER** -- the scan reports
it, RE showed it is a read (see the detector note). **UNVERIFIED** -- a real
"go look", not a clean bill of health.

## Two things that generalise, and both bite

### The LAUNDERING hole in this primitive

A recount (`gPlayerPartyCount = 0; ++ per non-empty slot`) is the commonest
shape in every one of these ROMs, and it is EXEMPT because it introduces
nothing. But it is also what makes a *direct* write into `gPlayerParty`
legitimate afterwards. So the party-count byte is an excellent primitive for
catching a routine that *adds* a mon and a poor one for catching a routine that
*writes the array and lets someone else recount*. That is the Platinum lesson --
*an inventory is only as good as its choice of PRIMITIVE* -- recurring one level
up rather than one idiom over. **A future pass should inventory writers of
`gPlayerParty` itself and reconcile the two sets.**

### The DETECTOR DEFECT that produces NOT-A-WRITER rows

The scan finds `ldr rX,[pc,#imm]` loading the count's address, then looks ahead
up to 60 instructions for a store through `rX`. It breaks on a re-`ldr` of
`rX`, on `bx`, and on `pop {..,pc}` -- but **not** when `rX` is clobbered by an
ordinary instruction (`ldrb rX,[rX]`, `movs rX,rY`), and **not** at an
unconditional branch, so the window can walk into a literal pool and decode a
data word as a store.

Both failure modes were confirmed here. They are safe -- the detector
over-reports, it does not miss -- so the sites stay inventoried rather than
being filtered out: dropping them would make the "nothing inventoried vanished"
check fail. Tightening the detector is a deliberate future change that must
re-baseline the inventory in the same commit.

"""

FOOTER = """
## Method, so it can be repeated

1. `arm-none-eabi-objdump -b binary -m armv4t -M force-thumb -D
   --adjust-vma=0x08000000 --start-address=... --stop-address=...`
2. Resolve the pc-relative pool by hand: `((pc + 4) & ~3) + imm * 4`.
3. Find the containing function by the nearest preceding `push {..,lr}` --
   then **verify it** by finding BL callers or pointer references to that
   entry. Where a candidate entry has neither, it is a mid-function push and
   the real entry is earlier; that happened twice here and both times the
   naive answer would have been wrong.
4. For a site claimed dead, scan the whole ROM for BL, `b`, `b<cond>` and u32
   pointers landing inside the orphaned range -- and read what any hits
   actually are. Coincidental matches inside sample data look exactly like
   pointer-table entries until you print their neighbours.
"""


def main():
    rows = sorted(chk.INVENTORY.items(),
                  key=lambda kv: (ORDER.get(kv[1][0], 9), kv[0]))
    out = [PREAMBLE, "## %s -- %d inventoried writer site(s)\n"
           % (chk.GAME, len(chk.INVENTORY))]
    for off, (verdict, why) in rows:
        out.append("### `%#010x` (file `%#010x`) -- **%s**\n"
                   % (0x08000000 + off, off, verdict))
        out.append(why + "\n")
    out.append(FOOTER)
    path = os.path.join(ROOT, "docs", "PARTY_COUNT_WRITERS.md")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote %s -- %d sites" % (os.path.relpath(path, ROOT),
                                    len(chk.INVENTORY)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
