#!/usr/bin/env python3
"""Generate ROSTERS.md / ROSTERS_SPRITES.md / sprites/gen_*.md from the data
the ROM actually enforces.

Why this exists: these docs used to be hand-maintained, and in the ROWE
reference project that produced a shipped doc promising 194 family bases the
catch gate refused while omitting thousands it already allowed. Here they are
read straight out of `rosters.bin` - the injected roster blob the enforcement
shim walks - so a doc entry cannot claim anything the ROM does not honour.

Inputs:
  rosters.bin               the injected per-character roster (u16 ids, 0-term)
  characters_manifest.json  character order, names, generation, category,
                            and each roster's offset into rosters.bin
  the DPE Unbound donor     species names, evolution table, National Dex map

"Final evolutions" = allowed species nothing else evolves them into. Mega and
Gigantamax rows in the evolution table are battle transformations, not
evolutions: counting them would drop every mega-capable species out of the
list. Species with no National Dex number (Unbound's alt forms) collapse onto
the base species they share a dex number with.

Run after emit_characters.py:
    python3 tools/character_mode/emit_roster_docs.py
"""
import importlib.util
import json
import os
import re
import struct
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))

GAME_TITLE = "Pokémon Unbound v2.1.1.1"
# Unbound has no Gen 9 content at all (verified in-ROM, see CLAUDE.md), so the
# dex tops out at Enamorus.
MAX_NATIONAL_DEX = 905
NON_EVOLUTION_METHODS = {"EVO_MEGA", "EVO_GIGANTAMAX"}

CATEGORY_LABEL = {
    "protagonist": "Protagonist", "rival": "Rival", "gymleader": "Gym Leader",
    "elite4": "Elite Four", "champion": "Champion", "villain": "Villain",
    "anime": "Anime", "professor": "Professor", "frontier": "Frontier Brain",
    # the Legends: Arceus cast, added by the 2026-07-25 roster audit. Without
    # these the fallback .title() renders "Galaxy" and "Other", which say
    # nothing about what the character actually is.
    "warden": "Warden", "galaxy": "Galaxy Team", "other": "Other",
}

# This donor spells regional variants with a constant suffix; it stops at Gen 8,
# so there are Hisuian and Alolan forms and no Galarian or Paldean ones.
REGION_SUFFIX_LABEL = {"_H": "Hisuian", "_A": "Alolan"}
# Trailing regional suffix on a SPECIES_* constant (SPECIES_GROWLITHE_H ->
# SPECIES_GROWLITHE), so a regional source label can also be filed under the
# ordinary family this ROM actually carries.
REGIONAL_CONST_RE = re.compile(r"(_H|_A|_G|_P)$")


def regional_form(const):
    """"Hisuian"/"Alolan" if this constant is a regional variant, else None.

    Regional forms get their OWN doc row (user, 2026-07-25): Growlithe and
    Hisuian Growlithe are two different Pokemon to a player, and the ROM allows
    both. They share a National Dex number, so without this they collapse onto
    one row and the doc under-reports what the character can actually catch.
    """
    for suffix, label in REGION_SUFFIX_LABEL.items():
        if const.endswith(suffix):
            return label
    return None


def load_unselectable():
    """Characters below the six-fully-evolved threshold, from
    character_drops.json (GENERATED by derive_drops.py).

    The gating IS injected now, so the docs are filtered -- but NOT by this
    list. They are filtered by the `hidden` field on each manifest record, i.e.
    by the CHAR_FLAG_HIDDEN bit actually emitted into the ROM, so the docs
    describe what the select screen really refuses rather than what a JSON file
    thinks it should. This list is kept as the cross-check: main() raises if the
    two ever disagree, which would mean emit_characters.py has not been re-run
    since derive_drops.py.
    """
    path = os.path.join(HERE, "character_drops.json")
    if not os.path.isfile(path):
        return []
    with open(path, encoding="utf-8") as f:
        return json.load(f).get("unselectable", [])


def load_sources():
    """{character: {owned species: {"source", "owned_form"}}} -- every
    provenance label this repo holds, from both files that carry one.

    `roster_sources.json` is the audit's attribution pass. But
    `roster_additions.json` ALSO records a source and owned_form per added
    species and nothing used to read them, so a family that entered a roster
    through the additions overlay showed a blank Source with its provenance
    sitting right there. roster_sources.json wins on conflict: it is the audit's
    considered answer.
    """
    merged = {}
    add_path = os.path.join(HERE, "roster_additions.json")
    if os.path.isfile(add_path):
        with open(add_path, encoding="utf-8") as f:
            for char, rows in json.load(f).get("additions", {}).items():
                for row in rows:
                    if not isinstance(row, dict) or not row.get("source"):
                        continue
                    merged.setdefault(char, {})[row["species"]] = {
                        "source": row["source"],
                        "owned_form": row.get("owned_form") or row["species"]}
    path = os.path.join(HERE, "roster_sources.json")
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            for char, rows in json.load(f).get("sources", {}).items():
                merged.setdefault(char, {}).update(rows)
    return merged


def rekey_sources_onto_family_base(sources, resolve_base):
    """{character: {family-base const: {owned name: info}}}.

    THE trap: the audit recorded the species each character OWNED ("Charizard"),
    but a roster stores the evolution-family BASE ("Charmander"), and the doc
    rows key off the base. Looked up as recorded, most keys match nothing and the
    Source column reads "—". Keeping the owned name in the inner dict is what
    lets a row say "as Charizard — Anime".
    """
    out = {}
    for char, rows in sources.items():
        if char.startswith("_"):
            continue
        per_base = {}
        for owned, info in rows.items():
            base = resolve_base(owned)
            if not base:
                continue
            per_base.setdefault(base, {})[owned] = info
            # A REGIONAL base is also filed under its ordinary base. "Hisuian
            # Arcanine" resolves to SPECIES_GROWLITHE_H, but this ROM has no
            # Hisuian forms, so map_species put PLAIN Growlithe on the roster
            # and the doc row's family base is SPECIES_GROWLITHE -- the keys
            # never met and the label was dropped. That was the last two blank
            # Source cells in the file (Volo's Arcanine, Zisu's Zoroark).
            # Filing it under both is safe: pick_source prefers an entry whose
            # name matches the row, so a character owning the ordinary form too
            # still gets the ordinary label, and where only the regional form is
            # owned the row honestly reads "as Hisuian Arcanine — ...".
            plain = REGIONAL_CONST_RE.sub("", base)
            if plain != base:
                per_base.setdefault(plain, {}).setdefault(owned, info)
        out[char] = per_base
    return out


PLACEHOLDER_FORMS = {"normal", "base", "none", "-", ""}


def source_cell(info, shown_name):
    """"as Bulbasaur — Anime (Indigo League)", or just the source when the
    character owned the shown stage itself."""
    src = (info or {}).get("source")
    if not src:
        return "—"
    owned = ((info or {}).get("owned_form") or "").strip()
    if owned and owned.lower() not in PLACEHOLDER_FORMS and owned != shown_name:
        return "as %s — %s" % (owned, src)
    return src


def pick_source(per_base, base_const, shown_name):
    """The best-matching source entry for one doc row, deterministically:
    the exact species shown, else one naming the family base, else the
    alphabetically first -- a family with several owned forms must not pick a
    different one on each run.

    Entries whose `source` is null are considered ONLY as a last resort. 24 of
    the audit's entries carry an owned_form but no source, and several of them
    sit in a family whose OTHER entry is perfectly well sourced -- Anabel's
    "Espeon" (null) was masking her "Eevee" ("Anime"), so the row printed "—"
    while the provenance was sitting right there in the same family. Preferring
    the exact species match is still correct; it just must not prefer a blank
    one over a real one."""
    entries = per_base.get(base_const) or {}
    if not entries:
        return {}
    sourced = {k: v for k, v in entries.items() if (v or {}).get("source")}
    pool = sourced or entries
    if shown_name in pool:
        return pool[shown_name]
    return pool[min(pool)]

SPRITE_URL = ("https://cdn.jsdelivr.net/gh/PokeAPI/sprites@master"
              "/sprites/pokemon/%d.png")
SPRITES_PER_ROW = 8


def load_map_species():
    """The pipeline's own resolver, reused so names/ids come from exactly the
    same donor files the roster data was built from."""
    spec = importlib.util.spec_from_file_location(
        "map_species", os.path.join(HERE, "map_species.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def evolution_children(donor, const_id):
    """species id -> [ids it really evolves into]."""
    text = open(os.path.join(donor, "src/Evolution Table.c"), encoding="utf-8").read()
    body = re.search(r"gEvolutionTable\[NUM_SPECIES\]\[EVOS_PER_MON\]\s*=\s*\{(.*?)^\};",
                     text, re.S | re.M).group(1)
    rows = [(r.start(), r.group(1)) for r in re.finditer(r"\[(SPECIES_\w+)\]\s*=", body)]
    kids = defaultdict(set)
    for t in re.finditer(r"\{\s*(EVO_\w+)\s*,[^,{}]+,\s*(SPECIES_\w+)", body):
        if t.group(1) in NON_EVOLUTION_METHODS:
            continue
        src = None
        for pos, name in rows:
            if pos < t.start():
                src = name
            else:
                break
        if not src or src == t.group(2):
            continue
        a, b = const_id.get(src), const_id.get(t.group(2))
        if a and b:
            kids[a].add(b)
    return kids


def national_dex(donor, const_id):
    """species id -> National Dex number, from the donor's own
    gSpeciesToNationalPokedexNum + pokedex.h."""
    header = open(os.path.join(donor, "include/pokedex.h"), encoding="utf-8").read()
    nums = {m.group(1): int(m.group(2))
            for m in re.finditer(r"#define\s+(NATIONAL_DEX_\w+)\s+(\d+)", header)}
    if not nums:                       # the header may spell it as an enum
        body = re.search(r"enum\s+\w*\s*\{(.*?)\}\s*;", header, re.S)
        if body:
            n = 0
            for line in body.group(1).splitlines():
                m = re.match(r"\s*(NATIONAL_DEX_\w+)\s*(?:=\s*(\d+))?\s*,", line)
                if not m:
                    continue
                if m.group(2):
                    n = int(m.group(2))
                nums[m.group(1)] = n
                n += 1
    table = open(os.path.join(donor, "src/Species_To_Pokdex_Table.c"),
                 encoding="utf-8").read()
    out = {}
    for m in re.finditer(r"\[(SPECIES_\w+)\s*-\s*1\]\s*=\s*(NATIONAL_DEX_\w+)", table):
        sid = const_id.get(m.group(1))
        if sid and m.group(2) in nums:
            out[sid] = nums[m.group(2)]
    return out


def rosters_from_blob(manifest):
    """[species ids] per character, read out of the injected rosters.bin."""
    blob = open(os.path.join(HERE, "rosters.bin"), "rb").read()
    out = []
    for rec in manifest:
        off, ids = rec["roster_offset"], []
        while True:
            (sid,) = struct.unpack_from("<H", blob, off)
            off += 2
            if sid == 0:               # SPECIES_NONE terminator
                break
            ids.append(sid)
        out.append(ids)
    return out


def main():
    ms = load_map_species()
    donor = ms.DONOR
    const_id = ms.species_ids()
    id_name = {v: k for k, v in ms.name_to_id().items()}
    kids = evolution_children(donor, const_id)
    dex = national_dex(donor, const_id)

    with open(os.path.join(HERE, "characters_manifest.json")) as f:
        manifest = json.load(f)["characters"]
    rosters = rosters_from_blob(manifest)

    # canonical species per dex number (the base form, i.e. the lowest id)
    canonical = {}
    for sid in sorted(dex):
        canonical.setdefault(dex[sid], sid)

    id_const = {v: k for k, v in const_id.items()}
    base_of = ms.first_stage_map()

    def resolve_base(name):
        """Owned display name -> family-base SPECIES_* constant, using the
        pipeline's own resolver so the source keys speak its language."""
        sid = ms.name_to_id().get(ms.NAME_FIXES.get(name, name))
        if sid is None:
            const = ms.regional_fallback(name, const_id, ms.name_to_id(), id_const)
            if const is None:
                pre = ms.GEN9_EVO_OF.get(name)
                const = (id_const.get(ms.name_to_id().get(ms.NAME_FIXES.get(pre, pre)))
                         if pre else None)
            return base_of.get(const, const) if const else None
        const = id_const.get(sid)
        return base_of.get(const, const) if const else None

    sources = rekey_sources_onto_family_base(load_sources(), resolve_base)

    # Characters the ROM refuses to let the player SELECT are not documented:
    # the project's rule is that the docs list what is offered. They keep their
    # table slot and their record (saves store the INDEX), so the numbering of
    # everyone else is untouched and simply has gaps.
    chars = []
    hidden_names = []
    for rec, ids in zip(manifest, rosters):
        if rec.get("hidden"):
            hidden_names.append(rec["character"])
            continue
        finals = {}
        for sid in ids:
            if kids.get(sid):
                continue
            num = dex.get(sid)
            if not num or num > MAX_NATIONAL_DEX:
                continue               # alt form with no dex entry of its own
            const = id_const.get(sid, "")
            if regional_form(const):
                shown = sid           # a regional form keeps its own row
            else:
                shown = canonical.get(num, sid)
                if kids.get(shown):
                    continue          # a cosmetic form of a species that evolves
            # the roster stores evolution-family bases and the audit is keyed by
            # them, so remember which base this row descends from
            finals.setdefault(shown, base_of.get(const, const))
        # The species id is the final tiebreak, and it is not decorative: a
        # regional form shares BOTH its dex number and its display name with the
        # base form, so without it the two rows sort equal and land in
        # set-iteration order, diffing on every regeneration with no data change.
        ordered = sorted(finals, key=lambda s: (dex[s], id_name.get(s, ""), s))
        char_sources = sources.get(rec["character"], {})
        rows = []
        for s in ordered:
            region = regional_form(id_const.get(s, ""))
            # name_to_id() keeps only the FIRST id per display name (the base
            # form), so inverting it has no entry for a regional variant at all --
            # that printed "Hisuian #1235" instead of "Hisuian Arcanine". Take the
            # name from the canonical species for this dex number, which is
            # exactly the base form whose name the variant shares.
            plain = id_name.get(canonical.get(dex[s], s)) or id_name.get(s) \
                or "#%d" % s
            shown_name = "%s %s" % (region, plain) if region else plain
            info = pick_source(char_sources, finals[s], plain)
            # compare against the SHOWN name, so a Hisuian row whose owned form is
            # "Hisuian Arcanine" prints the source plainly instead of the
            # redundant "as Hisuian Arcanine — ..."
            rows.append((shown_name, dex[s], source_cell(info, shown_name)))
        chars.append({
            "name": rec["character"],
            "gen": rec["generation"],
            "label": CATEGORY_LABEL.get(rec["category"], rec["category"].title()),
            "finals": rows,
        })

    by_gen = defaultdict(list)
    for c in chars:
        by_gen[c["gen"]].append(c)
    for g in by_gen:
        by_gen[g].sort(key=lambda c: c["name"])
    gens = sorted(by_gen)

    generated_note = ("GENERATED by `tools/character_mode/emit_roster_docs.py` "
                      "from `rosters.bin`, the same injected roster blob the "
                      "enforcement shim walks — do not hand-edit, regenerate.")
    dex_note = ("> Species above National Dex #%d are omitted (not present in "
                "this game)." % MAX_NATIONAL_DEX)

    # Coverage, stated rather than implied. Both numbers below have been wrong in
    # a shipped doc before: rows carried no provenance at all, and the character
    # count drifted from the ROM's.
    all_rows = [r for c in chars for r in c["finals"]]
    sourced = sum(1 for _n, _d, src in all_rows if src and src != "—")
    thin = sorted(load_unselectable())
    coverage = [
        "### Coverage", "",
        "- **%d characters**, **%d final-evolution rows**; every row is derived "
        "from `rosters.bin`, the injected blob the enforcement shim walks, so "
        "nothing here is promised that the ROM refuses."
        % (len(chars), len(all_rows)),
        "- **%d of %d rows (%.0f%%) carry a Source.** A blank Source means the "
        "provenance is not recorded, not that the entry is unverified — the "
        "2026-07-25 adversarial audit judged every roster in this file."
        % (sourced, len(all_rows), 100.0 * sourced / max(1, len(all_rows))),
    ]
    if hidden_names:
        coverage.append(
            "- **%d characters are hidden from the menu** and are therefore not "
            "listed here: %s. Each has fewer than six fully-evolved Pokémon "
            "obtainable in this game's dex, with no legendary to exempt it, so "
            "the character-select screen refuses the number. They keep their "
            "table slots — character ids are save data, so the remaining numbers "
            "are unchanged and simply skip these."
            % (len(hidden_names), ", ".join(sorted(hidden_names))))
    # thin (character_drops.json) and hidden (the emitted flag) must agree; if
    # they ever diverge, the docs would describe a gate the ROM does not have.
    if sorted(thin) != sorted(hidden_names):
        raise SystemExit(
            "character_drops.json and the emitted CHAR_FLAG_HIDDEN disagree:\n"
            "  only in character_drops.json: %s\n"
            "  only in the emitted records:  %s\n"
            "Re-run emit_characters.py after derive_drops.py."
            % (sorted(set(thin) - set(hidden_names)),
               sorted(set(hidden_names) - set(thin))))

    out = ["# Character Mode — Final-Evolution Rosters (%s)" % GAME_TITLE, "",
           "Every playable character and the **final evolutions** their complete "
           "roster resolves to, in **National Pokédex order**. Rosters were "
           "researched from Bulbapedia (union of all games, remakes, rematches, "
           "and anime) and cross-checked where possible. Regional/cosmetic forms "
           "show as their base species. Off-roster Pokémon are routed to your PC.",
           "", dex_note, "",
           "**%d characters.** Sprite version: `ROSTERS_SPRITES.md`." % len(chars),
           "", generated_note, ""] + coverage + ["", "## Contents"]
    for g in gens:
        out.append("- [Generation %d](#generation-%d)" % (g, g))
    out.append("")
    for g in gens:
        out += ["", "## Generation %d" % g, ""]
        for c in by_gen[g]:
            out.append("### %s — %s" % (c["name"], c["label"]))
            out.append("**Final evolutions (%d):**" % len(c["finals"]))
            out.append("")
            out.append("| Pokémon | Source |")
            out.append("|---|---|")
            for name, _dex, src in c["finals"]:
                out.append("| %s | %s |" % (name, src))
            out.append("")
    with open(os.path.join(TARGET, "ROSTERS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")

    idx = ["# Character Mode — Roster Sprites (%s)" % GAME_TITLE, "",
           "Each character's **final-evolution** roster, in **National Pokédex "
           "order**, with sprites and names. Split by generation to keep pages "
           "fast. Regional/cosmetic forms show as base species. Sprites via "
           "[PokéAPI](https://github.com/PokeAPI/sprites). Text: `ROSTERS.md`.",
           "", "**%d characters.**" % len(chars), "", generated_note,
           "", "## Generations", ""]
    for g in gens:
        idx.append("- [Generation %d](sprites/gen_%d.md) — %d characters"
                   % (g, g, len(by_gen[g])))
    with open(os.path.join(TARGET, "ROSTERS_SPRITES.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(idx).rstrip() + "\n")

    os.makedirs(os.path.join(TARGET, "sprites"), exist_ok=True)
    for g in gens:
        page = ["# %s — Roster Sprites (Generation %d)" % (GAME_TITLE, g), "",
                "Final-evolution rosters in National Pokédex order, sprites with "
                "names. [← back to index](../ROSTERS_SPRITES.md)", ""]
        for c in by_gen[g]:
            page.append("### %s — %s" % (c["name"], c["label"]))
            page.append("<table>")
            row = []
            for name, num, src in c["finals"]:
                note = ("<br><sub><i>%s</i></sub>" % src) if src and src != "—" else ""
                row.append('<td align="center" width="100"><img width="56" src="%s">'
                           "<br><sub>%s</sub>%s</td>"
                           % (SPRITE_URL % num, name, note))
                if len(row) == SPRITES_PER_ROW:
                    page.append("<tr>" + "".join(row) + "</tr>")
                    row = []
            if row:
                page.append("<tr>" + "".join(row) + "</tr>")
            page += ["</table>", ""]
        with open(os.path.join(TARGET, "sprites/gen_%d.md" % g), "w",
                  encoding="utf-8") as f:
            f.write("\n".join(page).rstrip() + "\n")

    print("wrote ROSTERS.md, ROSTERS_SPRITES.md and %d sprites/gen_*.md: "
          "%d characters, %d final-evolution entries"
          % (len(gens), len(chars), sum(len(c["finals"]) for c in chars)))


if __name__ == "__main__":
    main()
