#!/usr/bin/env python3
"""Emit roster_roots.bin -- the family ROOTS of each character's roster, in
authored order, for the in-game roster display.

Ported 2026-09-27 from the Seaglass/Lazarus ports' emit_roster_roots.py. The
blob LAYOUT is shared; this game is CFRU (FireRed), so the screen that reads it
is different (src/roster_display.c is a native task + list menu, not a
dynmultichoice callback set), and species ids are Unbound (DPE) ids, not national dex.

    +0x0000  entry[NUM_CHARACTERS]    u16 first_root, u16 root_count  (4 B each)
    +roots_offset  roots[total_roots] u16 species id

Duplicates are collapsed keeping the first occurrence (a roster is a SET in
enforcement, a LIST on screen), measured per dex, never copied.

There is no species-table JSON here. Names are checked against the BASE ROM's
own table: CFRU's redirect slot at file 0x144 -> gSpeciesNames (0x094042CC in
RR 4.1), 11 bytes per species, 0xFF-terminated.
"""
import json
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "roster_roots.bin")

ENTRY_SIZE = 4   # u16 first_root, u16 root_count
NAMES_SLOT = 0x144   # CFRU rom_locs.h: gSpeciesNames = *(u32 *)0x08000144
NAME_STRIDE = 11     # POKEMON_NAME_LENGTH + 1


def main():
    with open(os.path.join(HERE, "characters_manifest.json"), encoding="utf-8") as fh:
        manifest = json.load(fh)
    chars = manifest["characters"]
    # Derived, never hardcoded: a stale literal character count is the most
    # repeated bug in this workspace and it never presents AS a count error.
    n_chars = len(chars)
    assert n_chars == manifest["record_count"], (n_chars, manifest["record_count"])

    rom = open(os.path.join(HERE, "..", "..", "rom", "Pokemon Unbound (v2.1.1.1).gba"), "rb").read()
    names_base = struct.unpack_from("<I", rom, NAMES_SLOT)[0]
    assert 0x08000000 <= names_base < 0x0A000000, hex(names_base)

    def has_name(s):
        o = names_base - 0x08000000 + s * NAME_STRIDE
        return rom[o] not in (0x00, 0xFF) and 0xFF in rom[o:o + NAME_STRIDE]

    entries = bytearray()
    roots = bytearray()
    cursor = 0
    empty = []
    max_count = 0

    collapsed = []

    for c in chars:
        raw = c["roster_species_ids"]
        # Deduplicate, keeping first occurrence -- see the Rika note in the
        # module docstring. Recorded per character rather than silently dropped,
        # because a NEW collapse appearing here is a real signal about the dex.
        ids = list(dict.fromkeys(raw))
        if len(ids) != len(raw):
            collapsed.append({"character": c["character"],
                              "was": len(raw), "now": len(ids)})
        for s in ids:
            # A root with no name in this ROM would draw a blank row. Fail here
            # instead, where the id is still attributable to a character.
            assert has_name(s), (
                "%s: root species %d has no name in the ROM species table"
                % (c["character"], s))
            assert 0 < s <= 0xFFFF, (c["character"], s)
        assert len(set(ids)) == len(ids), (
            "%s: dedup failed" % c["character"])
        if not ids:
            empty.append(c["character"])
        max_count = max(max_count, len(ids))
        assert cursor <= 0xFFFF and len(ids) <= 0xFFFF, (c["character"], cursor)
        entries += struct.pack("<HH", cursor, len(ids))
        for s in ids:
            roots += struct.pack("<H", s)
        cursor += len(ids)

    total_roots = cursor
    blob = bytes(entries) + bytes(roots)
    expect = n_chars * ENTRY_SIZE + total_roots * 2
    assert len(blob) == expect, (len(blob), expect)
    # The emitter's own claim about where roots[] starts, checked rather than
    # asserted in a comment -- the shim is given this as -DROSTER_ROOTS_OFF.
    roots_off = n_chars * ENTRY_SIZE
    assert blob[roots_off:roots_off + 2] == struct.pack(
        "<H", chars[0]["roster_species_ids"][0]), "roots[] does not start where claimed"

    with open(OUT, "wb") as fh:
        fh.write(blob)

    # Emitted so verify_artifacts can re-derive the same answer independently
    # rather than trusting the .bin it is checking.
    with open(os.path.join(HERE, "roster_roots_manifest.json"), "w",
              encoding="utf-8") as fh:
        json.dump({
            "characters": n_chars,
            "total_roots": total_roots,
            "entry_size_bytes": ENTRY_SIZE,
            "roots_offset_bytes": roots_off,
            "blob_size_bytes": len(blob),
            "max_roots_per_character": max_count,
            "empty_roster": empty,
            "collapsed_duplicate_roots": collapsed,
            "species_table_base": "%#010x" % (names_base - 0x08000000),
            "species_table_stride": NAME_STRIDE,
            "_comment": "GENERATED by emit_roster_roots.py -- do not hand-edit",
        }, fh, indent=1)
        fh.write("\n")

    print("wrote %s: %d B (%d characters, %d roots, roots[] at +%#x)"
          % (OUT, len(blob), n_chars, total_roots, roots_off))
    print("  longest roster %d roots; %d empty (%s)"
          % (max_count, len(empty), ", ".join(empty) if empty else "none"))
    for cd in collapsed:
        print("  collapsed duplicate root: %s %d -> %d rows"
              % (cd["character"], cd["was"], cd["now"]))


if __name__ == "__main__":
    main()
